services:
  web:
    build: .
    ports:
      - "${WEB_PORT}:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - db

  db:
      image: mysql:8.0
      environment:
        MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
        MYSQL_DATABASE: ${MYSQL_DATABASE}
        MYSQL_USER: ${MYSQL_USER}
        MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      ports:
        - "${DB_PORT}:${DB_PORT}"
      volumes:
        - mysql-data:/var/lib/mysql
  phpmyadmin:
      image: phpmyadmin/phpmyadmin
      container_name: phpmyadmin
      depends_on:
        - db
      ports:
        - "${MYADMIN_PORT}:80"
      environment:
        PMA_HOST: db
        MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}

volumes:
  mysql-data:
